###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"  
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "fullname" . }} 
      labels:
        app: iibv10
    spec:
      imagePullSecrets:
      - name: admin.registrykey
      containers:
      - name: {{ template "fullname" . }} 
        image: "{{ .values.image }}"
        imagePullPolicy: "{{ .values.imagePullPolicy }}"
        ports:
        - containerPort: 7800
          name: serverlistener
        - containerPort: 7080
          name: nodelistener
        - containerPort: 4414
          name: webui
        env:
        -
         name : LICENSE
         value : {{ .values.license }}
        -
         name : NODENAME
         value : {{ .values.nodename }}
        -
         name : SERVERNAME
         value : {{ .values.servername }}
         
