###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
service:  
  type: NodePort
  webuiPort: 4414  
  serverlistenerPort: 7800
  nodelistenerPort: 7080
image:
  repository: ibmcom/iib
  tag: 10.0.0.10
  pullSecret: 
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 1
    memory: 512Mi
license: "Not accepted"
nodename: "IIB_NODE"
servername: "IIB_SERVER"
